import React from "react";
import '../../style/style-agreement.css'


function Agreement(){
    return(
        <div className="card-body-agree">
            <h3>ACUERDO DE USUARIO</h3>
            <p>
            AVISO A TODOS LOS USUARIOS: LEA DETENIDAMENTE ESTE ACUERDO. AL HACER CLIC EN EL BOTÓN ACEPTAR 
            O INSTALAR EL SOFTWARE, USTED (SEA UNA PERSONA FÍSICA O JURÍDICA) ACEPTA QUE ESTE ACUERDO ES 
            APLICABLE COMO CUALQUIER CONTRATO QUE HAYA FIRMADO. SI NO ESTÁ CONFORME, HAGA CLIC EN EL BOTÓN 
            QUE INDICA QUE NO ACEPTA LOS TÉRMINOS DE ESTE ACUERDO Y NO HAGA USO DEL SOFTWARE. SI HA ADQUIRIDO 
            EL SOFTWARE EN UN SOPORTE TANGIBLE (POR EJEMPLO, UN CD) SIN TENER LA OPORTUNIDAD DE EXAMINAR ESTA 
            LICENCIA Y NO ACEPTA ESTE ACUERDO, PODRÁ OBTENER UN REEMBOLSO DEL IMPORTE ABONADO SI: 
            (A) NO UTILIZA EL SOFTWARE Y (B) LO DEVUELVE, JUNTO CON LA PRUEBA DEL PAGO, EN UN PLAZO DE TREINTA
            (30) DÍAS A PARTIR DE LA FECHA DE COMPRA AL PUNTO DE VENTA DONDE LO ADQUIRIÓ
            </p>
        </div>
    );

}
export default Agreement;